import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Header from "./components/Header";

const roboto = Roboto({ subsets: ["latin"], weight: ["900", "700", "500"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${roboto.className} text-[#333] dark:text-[#9b9b9b]`}>
				<Providers>
					<Header />
					<main className="max-w-[90%] mx-auto">{children}</main>
				</Providers>
			</body>
		</html>
	);
}
