import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Header from "./components/Header";
import Footer from "./components/Footer";

const roboto = Roboto({ subsets: ["latin"], weight: ["900", "700", "500"] });

export const metadata: Metadata = {
	title: "Movies APP with Next 14",
	description: "Generated by create next app"
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${roboto.className} text-[#333] dark:text-[#9b9b9b]`}>
				<Providers>
					<Header />
					<main>{children}</main>
          <Footer />
				</Providers>
			</body>
		</html>
	);
}
